config/routes.rb
Rails.application.routes.draw do
  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.save
    redirect_to idea_path(@idea)
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    redirect_to idea_path(@idea)
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :img)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form_input.html.erb
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<%= f.label :img %>
<%= f.number_field :img %>
<br>
<%= f.submit %>

app/views/ideas/edit.html.erb
<%= form_for @idea do |humming| %>
  <%= render partial: 'form_input', locals: {f: humming} %>
<% end %>

app/views/ideas/index.html.erb
<%= link_to "작성하기", new_idea_path %>
<% @ideas.each do |i| %>
  <%= link_to idea_path(i) do %>
    <%= i.title %><br>
    <%= i.description %><br>
    <%= i.img %>
  <% end %>
  <hr>
<% end %>

app/views/ideas/new.html.erb
<%= form_for @idea do |humming| %>
  <%= label_tag :summary %>
  <%= text_field_tag :summary %><br>
  <%= render partial: 'form_input', locals: {f: humming} %>
<% end %>

app/views/ideas/show.html.erb
<%= @idea.title %><br>
<%= @idea.description %><br>
<%= @idea.img %><br>
<%= link_to "수정", edit_idea_path(@idea) %>
<%= link_to "삭제", idea_path(@idea), method: :delete %>
<%= link_to "뒤로가기", ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaTengtengee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>